"""Add telegram_user_id to users table

Revision ID: 7cf6df328347
Revises: 002
Create Date: 2026-02-24 16:13:18.504452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf6df328347'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_date', table_name='transactions')
    op.add_column('users', sa.Column('telegram_user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_column('users', 'telegram_user_id')
    op.create_index('ix_transactions_date', 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###
